// User's submitted function (this would come from their submission)
function twoSum(nums, target) {
    const map = new Map();
    for (let i = 0; i < nums.length; i++) {
        const complement = target - nums[i];
        if (map.has(complement)) {
            return [map.get(complement), i];
        }
        map.set(nums[i], i);
    }
    return [];
}

// Test harness (generated by your backend)
const testCases = [
    {
        input: { nums: [2, 7, 11, 15], target: 9 },
        expected: [0, 1],
        description: "Basic case: [2,7,11,15], target 9"
    },
    {
        input: { nums: [3, 2, 4], target: 6 },
        expected: [1, 2],
        description: "Case: [3,2,4], target 6"
    },
    {
        input: { nums: [3, 3], target: 6 },
        expected: [0, 1],
        description: "Duplicate numbers: [3,3], target 6"
    },
    {
        input: { nums: [1, 2, 3, 4, 5], target: 9 },
        expected: [3, 4],
        description: "Case: [1,2,3,4,5], target 9"
    }
];

function arraysEqual(a, b) {
    if (a.length !== b.length) return false;
    const sortedA = [...a].sort((x, y) => x - y);
    const sortedB = [...b].sort((x, y) => x - y);
    return sortedA.every((val, idx) => val === sortedB[idx]);
}

// Execute all test cases
const results = [];
testCases.forEach((testCase, index) => {
    try {
        const result = twoSum(testCase.input.nums, testCase.input.target);
        const passed = arraysEqual(result, testCase.expected);

        results.push({
            testCase: index + 1,
            description: testCase.description,
            input: testCase.input,
            expected: testCase.expected,
            actual: result,
            status: passed ? "PASS" : "FAIL"
        });
    } catch (error) {
        results.push({
            testCase: index + 1,
            description: testCase.description,
            input: testCase.input,
            expected: testCase.expected,
            actual: null,
            status: "ERROR",
            error: error.message
        });
    }
});

// Output structured results
console.log("=== TEST_RESULTS_START ===");
console.log(JSON.stringify(results, null, 2));
console.log("=== TEST_RESULTS_END ===");